name: Update Vietlott CSV

on:
  schedule:
    - cron: '0 0 * * *'   # chạy mỗi ngày 00:00 UTC (~07:00 VN)
  workflow_dispatch:       # cho phép chạy thủ công khi cần

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run crawler
        run: python crawler.py

      - name: Commit & push updated CSV
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add mega645.csv
        git commit -m "Auto update CSV" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
